version: '3.8'

services:
  app:
    image: rebhyy/kaddem:${BUILD_VERSION} # Use ${BUILD_VERSION} passed in the Jenkins pipeline
    container_name: kaddem-app
    ports:
      - "9009:9009" # Map port 9009 on the host to the app's port
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/kaddem?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
      - prometheus
      - grafana

  db:
    image: mysql:8
    container_name: kaddem-db
    ports:
      - "3306:3306" # Map port 3306 for MySQL access
    environment:
      MYSQL_DATABASE: kaddem
      MYSQL_ROOT_PASSWORD: root # Set the root password for MySQL here
    volumes:
      - db_data:/var/lib/mysql # Persist data in a named volume

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8089:80" # Map phpMyAdmin to port 8089 on the host
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    volumes:
      - phpmyadmin_data:/sessions # Persist phpMyAdmin sessions

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    depends_on:
      - prometheus


volumes:
  db_data: # Named volume to persist MySQL data
  phpmyadmin_data: # Named volume to persist phpMyAdmin sessions
