scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    scrape_interval: 5s

    static_configs:
      - targets: ['192.168.33.10:9090']

  - job_name: 'spring-boot-app'
    metrics_path: 'kaddem/actuator/prometheus'
    static_configs:
      - targets: ['192.168.33.10:8089']